### ISSUE TITLE
Missing release Git tags

### ISSUE THREAD

**Issue by szpak** [mdietrichstein/gradle-offline-dependencies-plugin#18]
The release tags have not been created (or most likely not pushed to GitHub). Therefore, people cannot be sure from which Git tag it was built and (probably more importantly) all people who starred the project (and enabled notifications about the new releases) are not informed about new releases.

**Comment by mdietrichstein** [comment]
You're right, prior releases actually did not have a release tag.

I have tagged the current version (0.5.0) and created a release on Github. Thanks for the suggestion/reminder ;)
