### ISSUE TITLE
publish the plugin

### ISSUE THREAD

**Issue by chrira** [mdietrichstein/gradle-offline-dependencies-plugin#2]
Please publish the plugin to the gradle plugin portal, such that not every one has to build it.
See: https://plugins.gradle.org/docs/submit
Thank you

**Comment by lukecwik** [comment]
I would also like to use this as well as I have tried many offline plugins for Gradle 4.x and this is the best one that I have found since it handled subprojects, parent poms, boms, etc...

Please publish.

**Comment by mdietrichstein** [comment]
Thanks for your feedback.

Took me a while, but I have published the plugin to `plugins.gradle.org`. Check out the updated integration instructions in this repo's README file.
